# Generated by Django 4.2.11 on 2024-04-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='image.photo', verbose_name='Изображения'),
        ),
    ]
